name = "prisma-d1-example"
main = "src/index.ts"
compatibility_date = "2024-04-04"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "prisma-demo-db"
database_id = "3d5b622c-b5d3-45ea-a3fb-574324adeeee"

[vars]
QUERY_BATCH_SIZE = 100